# Generated by Django 4.2.7 on 2025-07-11 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='language',
            field=models.CharField(choices=[('en', 'English (EN)'), ('ja', 'Japanese (JA)'), ('de', 'German (DE)'), ('fr', 'French (FR)'), ('es', 'Spanish (ES)'), ('it', 'Italian (IT)'), ('pt', 'Portuguese (PT)'), ('ko', 'Korean (KO)'), ('zh', 'Chinese (ZH)')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='variant',
            field=models.CharField(choices=[('normal', 'Normal'), ('reverse_holo', 'Reverse Holo'), ('holo', 'Holo'), ('first_edition', 'First Edition'), ('shadowless', 'Shadowless')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='collection',
            name='condition',
            field=models.CharField(choices=[('mint', 'Mint'), ('near_mint', 'Near Mint'), ('excellent', 'Excellent'), ('good', 'Good'), ('light_played', 'Light Played'), ('played', 'Played'), ('poor', 'Poor'), ('unspecified', 'Unspecified')], default='near_mint', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'card_id', 'condition', 'variant', 'language')},
        ),
    ]
